version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: vaultml-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: vaultml
      POSTGRES_PASSWORD: vaultmlpass
      POSTGRES_DB: vaultml
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: vaultml-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000" 
      - "9001:9001" 
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
