apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultml.fullname" . }}-secret
  labels:
    {{- include "vaultml.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.config.jwtSecret | b64enc | quote }}
  {{- if .Values.minio.enabled }}
  s3-access-key: {{ .Values.minio.auth.rootUser | b64enc | quote }}
  s3-secret-key: {{ .Values.minio.auth.rootPassword | b64enc | quote }}
  {{- else }}
  s3-access-key: {{ .Values.externalS3.accessKey | b64enc | quote }}
  s3-secret-key: {{ .Values.externalS3.secretKey | b64enc | quote }}
  {{- end }}